name:                f1racer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/f1racer#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - HUnit
  - linear
  - Yampa
  - simple-affine-space
  - gloss
  - cassava
  - bytestring
  - vector
  - split
  - containers
  
executables:
  f1racer:
    source-dirs:      src
    main:             Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs: 
      - test
      - src